import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { cpSync, existsSync, mkdirSync, mkdtempSync, readdirSync, readFileSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, resolve } from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const testDir = dirname(fileURLToPath(import.meta.url));
const piRoot = resolve(testDir, "..");
const repoRoot = resolve(piRoot, "..");
const profileDir = resolve(repoRoot, "plugins/awesome-agent-select/agent-profiles");
const codexDir = resolve(repoRoot, "plugins/awesome-agent-select/agents");
const piAgentsDir = resolve(piRoot, "subagents/awesome-agent-select");
const generator = resolve(repoRoot, "tools/generate-agent-adapters.mjs");

function fixture(run: (root: string) => void) {
	const root = mkdtempSync(resolve(tmpdir(), "agent-adapter-test-"));
	try {
		mkdirSync(resolve(root, "tools"));
		cpSync(generator, resolve(root, "tools/generate-agent-adapters.mjs"));
		cpSync(resolve(repoRoot, "plugins/awesome-agent-select"), resolve(root, "plugins/awesome-agent-select"), { recursive: true });
		cpSync(resolve(piRoot, "subagents"), resolve(root, "pi/subagents"), { recursive: true });
		run(root);
	} finally { rmSync(root, { recursive: true, force: true }); }
}

test("renaming and deleting canonical roles reconciles both hosts", () => {
	fixture((root) => {
		const profiles = resolve(root, "plugins/awesome-agent-select/agent-profiles");
		renameSync(resolve(profiles, "api-documenter.md"), resolve(profiles, "api-writer.md"));
		rmSync(resolve(profiles, "qa-expert.md"));
		const script = resolve(root, "tools/generate-agent-adapters.mjs");
		execFileSync(process.execPath, [script]);
		execFileSync(process.execPath, [script, "--check"]);
		for (const [dir, suffix] of [["plugins/awesome-agent-select/agents", ".toml"], ["pi/subagents/awesome-agent-select", ".md"]]) {
			assert.ok(existsSync(resolve(root, dir, `api-writer${suffix}`)));
			assert.ok(!existsSync(resolve(root, dir, `api-documenter${suffix}`)));
			assert.ok(!existsSync(resolve(root, dir, `qa-expert${suffix}`)));
		}
	});
});

test("unmanaged Pi output blocks generation before Codex files are changed", () => {
	fixture((root) => {
		const codex = resolve(root, "plugins/awesome-agent-select/agents/api-documenter.toml");
		const original = readFileSync(codex, "utf8");
		rmSync(resolve(root, "plugins/awesome-agent-select/agent-profiles/api-documenter.md"));
		const unmanaged = resolve(root, "pi/subagents/awesome-agent-select/custom.md");
		writeFileSync(unmanaged, "user instructions");
		assert.throws(() => execFileSync(process.execPath, [resolve(root, "tools/generate-agent-adapters.mjs")], { stdio: "pipe" }), /Refusing to remove unmanaged file/);
		assert.equal(readFileSync(codex, "utf8"), original);
		assert.equal(readFileSync(unmanaged, "utf8"), "user instructions");
	});
});

const names = (directory: string, suffix: string) => readdirSync(directory)
	.filter((name) => name.endsWith(suffix))
	.map((name) => name.slice(0, -suffix.length))
	.sort();

test("canonical role text renders current Codex and Pi adapters", () => {
	execFileSync(process.execPath, [generator, "--check"], {
		cwd: repoRoot,
		encoding: "utf8",
	});

	const profileNames = names(profileDir, ".md");
	assert.equal(profileNames.length, 10);
	assert.deepEqual(names(codexDir, ".toml"), profileNames);
	assert.deepEqual(names(piAgentsDir, ".md"), profileNames);

	for (const name of profileNames) {
		const profile = readFileSync(resolve(profileDir, `${name}.md`), "utf8");
		const [description, instructions] = profile.trimEnd().split("\n\n", 2);
		assert.ok(description.length > 0, `${name} needs a description paragraph`);
		assert.ok(instructions.length > 0, `${name} needs role instructions`);
		assert.doesNotMatch(profile, /^---\n/, `${name} source must not be host frontmatter`);
		assert.doesNotMatch(profile, /^name\s*=/m, `${name} source must not be TOML`);

		const codex = readFileSync(resolve(codexDir, `${name}.toml`), "utf8");
		assert.match(codex, /^# Generated by tools\/generate-agent-adapters\.mjs/m);
		assert.match(codex, new RegExp(`^name = "${name}"$`, "m"));
		assert.match(codex, /^description = /m);
		assert.match(codex, /^developer_instructions = '''$/m);
		assert.doesNotMatch(codex, /^(?:model|model_reasoning_effort)\s*=/m);

		const pi = readFileSync(resolve(piAgentsDir, `${name}.md`), "utf8");
		assert.match(pi, new RegExp(`^name: ${name}$`, "m"));
		assert.match(pi, /^package: cyberbrain$/m);
		assert.match(pi, /^description: /m);
		assert.match(pi, /^systemPromptMode: replace$/m);
		assert.doesNotMatch(pi, /^(?:model|thinking): /m);
	}
});
