import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { readdirSync, readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const testDir = dirname(fileURLToPath(import.meta.url));
const piRoot = resolve(testDir, "..");
const repoRoot = resolve(piRoot, "..");
const profileDir = resolve(repoRoot, "plugins/awesome-agent-select/agent-profiles");
const codexDir = resolve(repoRoot, "plugins/awesome-agent-select/agents");
const piAgentsDir = resolve(piRoot, "subagents/awesome-agent-select");
const generator = resolve(repoRoot, "tools/generate-agent-adapters.mjs");

const names = (directory: string, suffix: string) => readdirSync(directory)
	.filter((name) => name.endsWith(suffix))
	.map((name) => name.slice(0, -suffix.length))
	.sort();

test("canonical role text renders current Codex and Pi adapters", () => {
	execFileSync(process.execPath, [generator, "--check"], {
		cwd: repoRoot,
		encoding: "utf8",
	});

	const profileNames = names(profileDir, ".md");
	assert.equal(profileNames.length, 10);
	assert.deepEqual(names(codexDir, ".toml"), profileNames);
	assert.deepEqual(names(piAgentsDir, ".md"), profileNames);

	for (const name of profileNames) {
		const profile = readFileSync(resolve(profileDir, `${name}.md`), "utf8");
		const [description, instructions] = profile.trimEnd().split("\n\n", 2);
		assert.ok(description.length > 0, `${name} needs a description paragraph`);
		assert.ok(instructions.length > 0, `${name} needs role instructions`);
		assert.doesNotMatch(profile, /^---\n/, `${name} source must not be host frontmatter`);
		assert.doesNotMatch(profile, /^name\s*=/m, `${name} source must not be TOML`);

		const codex = readFileSync(resolve(codexDir, `${name}.toml`), "utf8");
		assert.match(codex, /^# Generated by tools\/generate-agent-adapters\.mjs/m);
		assert.match(codex, new RegExp(`^name = "${name}"$`, "m"));
		assert.match(codex, /^description = /m);
		assert.match(codex, /^developer_instructions = '''$/m);
		assert.doesNotMatch(codex, /^(?:model|model_reasoning_effort)\s*=/m);

		const pi = readFileSync(resolve(piAgentsDir, `${name}.md`), "utf8");
		assert.match(pi, new RegExp(`^name: ${name}$`, "m"));
		assert.match(pi, /^package: cyberbrain$/m);
		assert.match(pi, /^description: /m);
		assert.match(pi, /^systemPromptMode: replace$/m);
		assert.doesNotMatch(pi, /^(?:model|thinking): /m);
	}
});
